### ISSUE TITLE
npm run dev ？

### ISSUE THREAD

**Issue by changshengee** [PeachT/Electron-ng-alain#1]
"dev": "concurrently \"ng serve\" \"electron . --dev\"",
还是？
"dev": "concurrently \"ng serve\" \"electron ./app --dev\"",
我用楼主的不好使啊？

**Comment by GitYonglin** [comment]
@changshengee 
（根目录和/app）两个文件下都要npm i 还原一下包
concurrently 这个是一个npm包 您需要全局安装一下
npm i -g concurrently
